/**
 * 可配置的数据类型
 */
const DataTypes = {
    ABSTRACT: DataTypeAbstract,
    STRING: DataTypeString,
    CHAR: DataTypeChar,
    TEXT: DataTypeText,
    NUMBER: DataTypeNumber,
    TINYINT: DataTypeTinyInt,
    SMALLINT: DataTypeSmallInt,
    MEDIUMINT: DataTypeMediumInt,
    INTEGER: DataTypeInteger,
    BIGINT: DataTypeBigInt,
    FLOAT: DataTypeFloat,
    TIME: DataTypeTime,
    DATE: DataTypeDate,
    DATEONLY: DataTypeDateOnly,
    BOOLEAN: DataTypeBoolean,
    NOW: DataTypeNow,
    BLOB: DataTypeBlob,
    DECIMAL: DataTypeDecimal,
    NUMERIC: DataTypeDecimal,
    UUID: DataTypeUUID,
    UUIDV1: DataTypeUUIDv1,
    UUIDV4: DataTypeUUIDv4,
    HSTORE: DataTypeHStore,
    JSON: DataTypeJSONType,
    JSONB: DataTypeJSONB,
    VIRTUAL: DataTypeVirtual,
    ARRAY: DataTypeArray,
    NONE: DataTypeVirtual,
    ENUM: DataTypeEnum,
    RANGE: DataTypeRange,
    REAL: DataTypeReal,
    DOUBLE: DataTypeDouble,
    "DOUBLE PRECISION": DataTypeDouble,
    GEOMETRY: DataTypeGeometry,
}
module.exports = DataTypes;